- hosts: ubuntu22 
  become: yes
  tasks:
  - name: Create group kaizen
    group:
      name: kaizen
      state: present
  
  - name: Create group devops
    group:
      name: devops
      state: present

  - name: Create group qa
    group:
      name: qa
      state: present

  - name: Create user Munara
    user:
      name: Munara
      groups: kaizen, qa
      state: present
  
  - name: Create user tester 
    user:
      name: tester
      groups: qa
      state: present

# run the command: ansible-playbook groups_users.yml -i my_hosts
# Copy Homework1 folder to a remote machine:
# scp -r /root/ansible-homework-batch5/Homework1/ root@167.172.251.184:/root/