# tasks file for roles
- name: Download wordpress
  get_url: 
    url: "{{ url }}"
    dest: "{{ archive_file }}"

- name: Extract file
  unarchive:
    src: "{{ archive_file }}"
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: "{{ user_og }}"
    group: "{{ user_og }}"
    mode: '0755'
    remote_src: yes

- name: Template a file to html folder
  ansible.builtin.template:
    src: roles/Wordpress/templates/wp-config-sample.php.j2
    dest: /var/www/html/wp-config.php

- name: Restart apache
  service: 
    name: "{{ apache }}"
    state: restarted


 