# tasks file for roles

- name: Start and enable
  service: 
    name: mariadb
    state: started
    enabled: yes

- name: Create a new database with name '"{{ db_name }}"'
  community.mysql.mysql_db:
    login_user: munara241
    login_password: newdb1
    name: "{{ db_name }}"
    state: present

- name: Create database user with name 'munara' and password 'passwrd' with all database privileges
  community.mysql.mysql_user:
    login_user: munara241
    login_password: newdb1
    name: "{{ db_user }}"
    password: "{{ passwrd }}"
    priv: '*.*:ALL'
    state: present
    column_case_sensitive: false
